platform :ios, '11.0'
use_frameworks!

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '/Users/stewan/dev/capacitor'
  pod 'CapacitorCordova', :path => '/Users/stewan/dev/capacitor'
  
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
